# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c69f81fd956a8c6a375994f2d3c77115"
application_url = "https://turns-mathematics-wearing-alberta.trycloudflare.com"
embedded = true
name = "AI Transcreation Otto"
handle = "ai-transcreation-otto"

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_content,read_customer_events,read_files,read_legal_policies,read_locales,read_locations,read_markets,read_metaobject_definitions,read_metaobjects,read_online_store_navigation,read_online_store_pages,read_orders,read_privacy_settings,read_shipping,read_themes,read_translations,write_files,write_products,write_themes,write_translations"

[auth]
redirect_urls = [
  "https://turns-mathematics-wearing-alberta.trycloudflare.com/auth/callback",
  "https://turns-mathematics-wearing-alberta.trycloudflare.com/auth/shopify/callback",
  "https://turns-mathematics-wearing-alberta.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
