name = "remix"
roles = ["frontend", "backend"]
webhooks_path = "/webhooks/app/uninstalled"

[commands]
predev = "npx prisma generate"
dev_sqlite = "npx prisma migrate deploy && npm exec remix vite:dev"
dev = "npx prisma db push && npm exec remix vite:dev"
