# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "12967b2878cb1061e5ea705aaaab9f68"
name = "AI Transcreation Andrei"
handle = "ai-transcreation-andrei"
application_url = "https://citation-mf-sue-anne.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_content,read_customer_events,read_files,read_legal_policies,read_locales,read_locations,read_markets,read_metaobject_definitions,read_metaobjects,read_online_store_navigation,read_online_store_pages,read_orders,read_privacy_settings,read_shipping,read_themes,read_translations,write_files,write_products,write_themes,write_translations"

[auth]
redirect_urls = [
  "https://citation-mf-sue-anne.trycloudflare.com/auth/callback",
  "https://citation-mf-sue-anne.trycloudflare.com/auth/shopify/callback",
  "https://citation-mf-sue-anne.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
