# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "92cdb7afa95558f737349f0bf62a35a9"
application_url = "https://physician-forbidden-numerical-handed.trycloudflare.com"
embedded = true
name = "Transcreation Accelerator"
handle = "transcreation-accelerator-2"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_content,read_customer_events,read_files,read_legal_policies,read_locales,read_locations,read_markets,read_metaobject_definitions,read_metaobjects,read_online_store_navigation,read_online_store_pages,read_orders,read_privacy_settings,read_shipping,read_themes,read_translations,write_products,write_themes"

[auth]
redirect_urls = [
  "https://physician-forbidden-numerical-handed.trycloudflare.com/auth/callback",
  "https://physician-forbidden-numerical-handed.trycloudflare.com/auth/shopify/callback",
  "https://physician-forbidden-numerical-handed.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
